import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({headless:true});
try {
  const page=await browser.newPage({viewport:{width:1600,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8195');
  await page.getByRole('button',{name:'New song',exact:true}).click();
  await expect(page.getByRole('button',{name:'Provide original lyrics',exact:false})).toHaveCount(0);
  await page.getByRole('button',{name:'Make a cover',exact:true}).click();
  await page.getByRole('button',{name:'Provide original lyrics',exact:false}).click();
  await expect(page.getByLabel('Original lyrics',{exact:true})).toBeVisible();
  await expect(page.getByLabel('Lyric source')).toHaveValue('original');
  await page.locator('.composer-tabs').getByRole('button',{name:'Sound',exact:true}).click();
  await expect(page.getByLabel('Brief template')).toBeVisible();
  await page.getByLabel('Brief template').selectOption('metal/nu-metal-vocal');
  await page.getByRole('button',{name:'Reset all to template',exact:true}).click();
  await expect(page.getByLabel('Describe your sound')).toHaveValue('');
  await expect(page.getByRole('button',{name:'Copy template text',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'Copy template text',exact:true}).click();
  await expect(page.getByLabel('Describe your sound')).not.toHaveValue('');
  await page.locator('.composer-tabs').getByRole('button',{name:'Lyrics',exact:true}).click();
  await page.getByLabel('Lyric source').selectOption('original');
  await expect(page.getByLabel('Vocals',{exact:true})).toHaveValue('original lyrics');
  await page.getByLabel('Original lyrics',{exact:true}).fill('[Verse]\nI hear the thunder tonight\n[Chorus]\nWe rise into the light');
  await page.reload();
  await page.locator('.composer-tabs').getByRole('button',{name:'Lyrics',exact:true}).click();
  await expect(page.getByLabel('Original lyrics',{exact:true})).toHaveValue(/thunder/);
  let payload;
  await page.route('**/api/generate',async route=>{payload=route.request().postDataJSON();await route.fulfill({json:{ids:['test-original']}})});
  await page.getByRole('button',{name:'Create cover',exact:false}).click();
  await expect.poll(()=>payload?.lyricsMode).toBe('original');
  expect(payload.originalLyrics).toContain('thunder');
  expect(payload.fields.vocals).toBe('original lyrics');
  await expect(page.getByRole('button',{name:'Create cover',exact:false})).toBeEnabled();
  await page.getByLabel('Original lyrics',{exact:true}).scrollIntoViewIfNeeded();
  await page.screenshot({path:'tests/original-lyrics.png'});
  await page.getByLabel('Vocals',{exact:true}).selectOption('instrumental');
  await expect(page.getByLabel('Lyric source')).toHaveValue('auto');
  await expect(page.getByLabel('Original lyrics',{exact:true})).toHaveCount(0);
  await page.getByLabel('Lyric source').selectOption('manual');
  await expect(page.getByLabel('Vocals',{exact:true})).toHaveValue('new lyrics');
  await expect(page.getByLabel('Custom lyrics')).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  await page.getByLabel('Lyric source').selectOption('original');
  await page.screenshot({path:'tests/original-lyrics-mobile.png'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
  console.log('PASS: native template fills, source lyrics persistence, intercepted submission, mode switching, mobile layout.');
} finally {await browser.close()}
