import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:1600,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const tracks=(await (await page.request.get('http://127.0.0.1:8195/api/library')).json()).slice(0,3).map(t=>({...t,projectId:null}));
 let projects=[],submitted;
 await page.route('**/api/projects',async r=>{if(r.request().method()==='POST'){const d=r.request().postDataJSON();const p={...projects.find(p=>p.id===d.id),...d,id:d.id||'test-project'};projects=projects.filter(x=>x.id!==p.id).concat(p);await r.fulfill({json:p})}else await r.fulfill({json:projects})});
 await page.route('**/api/library',r=>r.fulfill({json:tracks}));
 await page.route('**/api/tracks/*/project',async r=>{const id=r.request().url().split('/').at(-2);tracks.find(t=>t.id===id).projectId=r.request().postDataJSON().projectId;await r.fulfill({json:{ok:true}})});
 await page.route('**/api/generate',async r=>{submitted=r.request().postDataJSON();await r.fulfill({json:{ids:['test-take']}})});
 await page.goto('http://127.0.0.1:8195');
 await page.getByRole('button',{name:'Projects',exact:true}).click();
 await page.getByLabel('Project name',{exact:true}).fill('Cover sessions');
 await page.getByRole('button',{name:'Create project',exact:true}).click();
 await expect(page.locator('.project-current')).toContainText('Cover sessions');
 await expect(page.locator('.track')).toHaveCount(0);
 await page.getByRole('button',{name:'My library',exact:false}).click();
 await page.locator('.track-menu summary').first().click();
 await page.locator('.track-menu[open] select').selectOption('test-project');
 await expect.poll(()=>tracks[0].projectId).toBe('test-project');
 await page.locator('.track-menu[open]').getByRole('button',{name:'Load in editor'}).click();
 await expect(page.getByLabel('Generation project')).toHaveValue('test-project');
 await expect(page.getByLabel(/^lyrics document/)).toBeVisible();
 await page.getByLabel(/^lyrics document/).fill('[Verse]\nA new lyric for this cover');
 await page.getByRole('button',{name:'Save draft',exact:true}).click();
 await expect.poll(()=>Boolean(projects[0]?.draft)).toBe(true);
 await page.getByRole('button',{name:'Create next take'}).click();
 await expect.poll(()=>submitted?.projectId).toBe('test-project');
 expect(submitted.baseTrack).toBe(tracks[0].id);
 expect(submitted.lyricsIntent).toBe('custom');
 expect(submitted.fields.vocals).toBe('new lyrics');
 await page.getByRole('button',{name:'Projects',exact:true}).click();
 await expect(page.locator('.track')).toHaveCount(1);
 await page.screenshot({path:'tests/projects.png'});
 await page.reload();await page.getByRole('button',{name:'Projects',exact:true}).click();
 await page.locator('.project-cards button').filter({hasText:'Cover sessions'}).click();
 await page.getByRole('button',{name:'Load saved draft'}).click();
 await expect(page.getByLabel(/^lyrics document/)).toHaveValue('[Verse]\nA new lyric for this cover');
 await page.getByRole('button',{name:'Studio',exact:true}).click();
 await page.locator('.composer-tabs').getByRole('button',{name:'Lyrics',exact:true}).click();
 await page.getByLabel('Lyric source',{exact:true}).selectOption('manual');
 await page.getByLabel('Custom lyrics',{exact:true}).fill('[Verse]\nMy pasted lyrics');
 await page.getByRole('button',{name:'Create cover',exact:false}).click();
 await expect.poll(()=>submitted?.lyrics).toBe('[Verse]\nMy pasted lyrics');
 expect(Object.values(submitted.sheetEdits).some(s=>s.lyrics)).toBe(false);
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'My library',exact:false}).click();
 await page.locator('.track-menu summary').first().click();
 await expect(page.locator('.track-menu[open]').getByRole('button',{name:'Load in editor'})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect(errors).toEqual([]);
 console.log('PASS: project creation, assignment, editor loading, custom cover lyrics, draft save/load, project filtering, mobile menus. Persistence/submissions intercepted; no real tracks changed.');
}finally{await browser.close()}
