import { chromium, expect } from '@playwright/test';
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:1600,height:1000}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8195');
await expect(page.locator('.track').first()).toBeVisible();
const tracks=await page.locator('.track').count();
await expect(page.locator('.waveform i').first()).toBeAttached({timeout:60000});
await page.getByRole('button',{name:'Play',exact:true}).click();
await expect.poll(()=>page.locator('audio').evaluate(a=>a.currentTime)).toBeGreaterThan(0);
await page.getByRole('button',{name:'Pause',exact:true}).click();
await page.getByPlaceholder(/Find your next favorite/).fill('unfindable-gimmemusic-test');
await expect(page.getByText('No tracks found.')).toBeVisible();
await page.getByPlaceholder(/Find your next favorite/).fill('');
const heart=page.locator('.track').first().locator('.track-actions > button');
const prior=await heart.getAttribute('aria-label');
await heart.click();
await expect(heart).not.toHaveAttribute('aria-label',prior);
await heart.click();
await expect(heart).toHaveAttribute('aria-label',prior);
await page.getByRole('button',{name:'New song',exact:true}).click();
await page.getByRole('button',{name:'Controls',exact:true}).click();
await page.getByLabel('Number of takes').selectOption('2');
let submitted;
await page.route('**/api/generate',async route=>{submitted=route.request().postDataJSON();await route.fulfill({json:{ids:['test-one','test-two']}})});
await page.getByRole('button',{name:'Create music',exact:false}).click();
await expect.poll(()=>submitted?.count).toBe(2);
expect(submitted.profile).toBe('song');
expect(submitted.randomize).toBe(true);
await expect(page.getByText('2 takes queued.',{exact:false})).toBeVisible();
await page.getByRole('button',{name:'Make a cover',exact:true}).click();
await page.screenshot({path:'tests/desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'tests/mobile.png',fullPage:true});
expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
expect(errors).toEqual([]);
const media=await page.locator('audio').getAttribute('src');
const range=await page.request.get('http://127.0.0.1:8195'+media,{headers:{Range:'bytes=0-1023'}});
expect(range.status()).toBe(206);
const csrf=await page.request.post('http://127.0.0.1:8195/api/generate',{headers:{Origin:'https://example.com'},data:{}});
expect(csrf.status()).toBe(403);
console.log(JSON.stringify({tracks,checks:'playback, waveform, search, favorites, profile switching, batch submission (mocked), mobile overflow, media ranges, origin protection',pageErrors:errors}));
await browser.close();
