import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({headless:true});
try{
  const page=await browser.newPage({viewport:{width:1600,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8195');
  await expect(page.getByLabel('Song title',{exact:true})).toBeVisible();
  await page.getByLabel('Song title',{exact:true}).fill('The Shape of Thunder');
  await page.getByRole('button',{name:'Song Sheet',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Song Sheet.',exact:true})).toBeVisible();
  const title=page.getByLabel(/^title document/);
  await expect(title).toHaveValue('The Shape of Thunder');
  await page.getByLabel(/^style mode/).selectOption('manual');
  await page.getByLabel(/^style document/).fill('Heavy guitars with expressive tom fills.');
  await page.screenshot({path:'tests/song-sheet.png',fullPage:true});
  let payload;
  await page.route('**/api/generate',async route=>{payload=route.request().postDataJSON();await route.fulfill({json:{ids:['editor-test']}})});
  await page.getByRole('button',{name:'Create next take'}).click();
  await expect.poll(()=>payload?.title).toBe('The Shape of Thunder');
  expect(Object.values(payload.sheetEdits).some(s=>s.style?.text.includes('expressive'))).toBe(true);
  await page.getByRole('button',{name:'Workflow settings',exact:true}).click();
  await page.getByLabel('Search workflow settings').fill('KSampler');
  const steps=page.getByLabel(/\/ steps$/);
  await expect(steps).toBeVisible();await steps.fill('24');
  await page.getByRole('button',{name:'Create next take'}).click();
  await expect.poll(()=>Object.values(payload.nodeInputs||{}).some(n=>n.steps===24)).toBe(true);
  await page.getByRole('button',{name:'Song Sheet',exact:true}).click();
  await page.getByRole('button',{name:'Saved releases',exact:true}).click();
  await expect(page.getByRole('button',{name:'Use for next take'})).toBeVisible();
  await page.getByRole('button',{name:'Use for next take'}).click();
  await page.getByRole('button',{name:'Create next take'}).click();
  await expect.poll(()=>Boolean(payload?.baseTrack)).toBe(true);
  await page.reload();await page.getByRole('button',{name:'Song Sheet',exact:true}).click();
  await expect(page.getByText('Using the selected release’s saved graph.',{exact:false})).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByLabel(/^title document/)).toBeAttached();
  await page.screenshot({path:'tests/song-sheet-mobile.png'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
  console.log('PASS: naming, sheet edits, sampler settings, release reuse, persistent drafts, mobile; submissions intercepted.');
}finally{await browser.close()}
